### ISSUE TITLE
Installation Guide incomplete

### ISSUE THREAD

**Issue by ocaner-biz** [leighmcculloch/sshagentsign#1]
Please enhance the installation guide, I wasn't able to build the sshcrypt project according to the documentation:

## Install

```
go get github.com/leighmcculloch/sshcrypt/...
```

**Comment by leighmcculloch** [comment]
What error did you encounter?

**Comment by ocaner-biz** [comment]
When the `GOPATH` enviroment variable isn't set the `go get ...` command doesn't do anything.

IMHO therefore the guide should be extended as follows:
```
export GOPATH=$(pwd)
go get github.com/leighmcculloch/sshcrypt/...
```
That was the error I've encountered.

Thanks for your fast response <3

**Comment by leighmcculloch** [comment]
Using `go get` is installing from source and all the go projects I've seen make this assumed knowledge that the GOPATH needs to be set.

I think what we need to resolve this is install instructions that install from a pre built binary so that there's no dependence on go and no knowledge required for how to install it.

**Comment by leighmcculloch** [comment]
@ocaner-biz: What platform and architecture do you use `sshcrypt` on? I'd like to release binaries, and can make sure to support yours.
